var wujian_all = {
  "status": "ok",
  "count": 36,
  "pages": 1,
  "category": {
    "id": 437,
    "slug": "hulaisanguo2-youxiziliao-wujiang",
    "title": "胡莱三国2-游戏资料-武将",
    "description": "",
    "parent": 432,
    "post_count": 36
  },
  "posts": [{
    "id": 13171,
    "type": "post",
    "slug": "%e4%ba%8e%e7%a6%81-2",
    "url": "http://games.hoolai.com/cms/?p=13171",
    "status": "publish",
    "title": "于禁",
    "title_plain": "于禁",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:57:22",
    "modified": "2017-06-15 17:57:22",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/于禁.png"],
      "初始品质": ["紫色"],
      "武将类型": ["防御"],
      "描述": ["于禁，字文则，泰山钜平（今山东泰安南）人。本为鲍信部将，后属曹操，曾于张绣造反时讨伐不守军纪的青州兵，同时为迎击敌军而固守营垒，因此曹操称赞他可与古代名将相比。然而在建安二十四年（219年）的襄樊之战中，于禁在败给关羽后投降，致使晚节不保。关羽败亡后，于禁从荆州获释到了吴国。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13170,
    "type": "post",
    "slug": "%e9%a2%9c%e8%89%af",
    "url": "http://games.hoolai.com/cms/?p=13170",
    "status": "publish",
    "title": "颜良",
    "title_plain": "颜良",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:55:56",
    "modified": "2017-06-15 17:55:56",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/颜良.png"],
      "初始品质": ["蓝色"],
      "武将类型": ["辅助"],
      "描述": ["颜良，东汉末年河北军阀袁绍部将，以勇而闻名。建安四年（199年），袁绍以颜良、文丑为将，率精卒十万，准备进攻河南许昌。建安五年（200年），兵进黎阳，遣颜良攻白马（今河南滑县）。曹操北救，以荀攸计分兵渡河，引袁绍西应，自率轻兵掩袭白马，颜良仓猝逆战，被关羽击斩。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13164,
    "type": "post",
    "slug": "%e8%8d%80%e5%bd%a7-2",
    "url": "http://games.hoolai.com/cms/?p=13164",
    "status": "publish",
    "title": "荀彧",
    "title_plain": "荀彧",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:53:06",
    "modified": "2017-06-16 16:04:17",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/荀彧.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["荀彧，字文若。颍川颍阴（今河南许昌）人。东汉末年著名政治家、战略家，曹操统一北方的首席谋臣和功臣，被称为“王佐之才”。在战略方面为曹操规划制定了统一北方的蓝图和军事路线；战术方面曾面对吕布叛乱而保全兖州三城，奇谋扼袁绍于官渡，险出宛、叶而间行轻进以掩其不意奇袭荆州等诸多建树；政治方面为曹操举荐了钟繇、荀攸、陈群、杜袭、戏志才、郭嘉等大量人才。荀彧在建计、密谋、匡弼、举人多有建树，被曹操称为“吾之子房”。"],
      "可晋升": ["橙色"],
      "获取途径": ["擂台商店"],
      "首页": ["否"]
    }
  }, {
    "id": 13163,
    "type": "post",
    "slug": "%e8%ae%b8%e8%a4%9a-2",
    "url": "http://games.hoolai.com/cms/?p=13163",
    "status": "publish",
    "title": "许褚",
    "title_plain": "许褚",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:50:58",
    "modified": "2017-06-15 18:06:40",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/许褚.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["许褚，字仲康，谯国谯人（今安徽亳州）。长八尺馀，腰大十围，容貌雄毅，勇力绝人。自典韦战死之后，主要负责曹操的护卫工作。官渡之战时发现欲谋害曹操者，将刺客全部杀掉。在与马超、韩遂会面时只让许褚相随，期间马超欲袭曹操，但听闻许褚之名兼怀疑从骑就是许褚，便问曹操虎侯安在，曹操指着许褚，许褚怒视马超以令他放弃。当曹操去世时许褚哭至吐血。"],
      "可晋升": ["橙色"],
      "获取途径": ["联盟商店"],
      "首页": ["否"]
    }
  }, {
    "id": 13162,
    "type": "post",
    "slug": "%e5%be%90%e5%ba%b6",
    "url": "http://games.hoolai.com/cms/?p=13162",
    "status": "publish",
    "title": "徐庶",
    "title_plain": "徐庶",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:49:51",
    "modified": "2017-06-16 16:05:04",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/徐庶.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["徐庶，字元直。颍川郡长社县（今河南许昌长葛东）人。徐庶本名徐福，为寒门子弟。早年为人报仇，获救后改名徐庶，求学于儒舍。后与同郡石广元避难于荆州，与司马徽、诸葛亮、崔州平等人为友。刘备屯驻新野时，徐庶前往投奔，并向刘备推荐诸葛亮。徐庶南下时因母亲被曹操所掳获，徐庶不得已辞别刘备，进入曹营。后来此事被艺术加工为“徐庶进曹营，一言不发”等歇后语，被广为流传。而徐庶也成为孝子的典范被加以称赞。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["否"]
    }
  }, {
    "id": 13161,
    "type": "post",
    "slug": "%e6%96%87%e4%b8%91",
    "url": "http://games.hoolai.com/cms/?p=13161",
    "status": "publish",
    "title": "文丑",
    "title_plain": "文丑",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:46:15",
    "modified": "2017-06-15 18:04:03",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/文丑、.png"],
      "初始品质": ["蓝色"],
      "武将类型": ["攻击"],
      "描述": ["文丑，东汉末年冀州牧袁绍帐下的大将。建安五年（200年），袁绍命文丑率军于延津攻曹操，曹操以诱敌之计大破文丑一军，文丑于此战中丧生。在小说《三国演义》中根据此段历史描写关羽斩文丑的故事，并广泛流传于后世。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["否"]
    }
  }, {
    "id": 13160,
    "type": "post",
    "slug": "%e5%90%95%e5%b8%83-2",
    "url": "http://games.hoolai.com/cms/?p=13160",
    "status": "publish",
    "title": "吕布",
    "title_plain": "吕布",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:44:29",
    "modified": "2017-06-15 17:44:29",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/吕布.png"],
      "初始品质": ["橙色"],
      "武将类型": ["攻击"],
      "描述": ["吕布，字奉先，五原郡九原县人（今内蒙古包头九原区），东汉末年名将，汉末群雄之一。先后为丁原、董卓的部将，后与司徒王允合力诛杀董卓失败，依附袁绍。与曹操争夺兖州失败后，吕布袭取徐州，割据一方。建安三年十二月（199年2月）吕布于下邳被曹操击败并处死。《三国演义》及各种民间艺术中被认为是“三国第一猛将”。"],
      "可晋升": ["橙色"],
      "获取途径": ["皇宫宝藏"],
      "首页": ["是"]
    }
  }, {
    "id": 13148,
    "type": "post",
    "slug": "%e7%a5%9d%e8%9e%8d-2",
    "url": "http://games.hoolai.com/cms/?p=13148",
    "status": "publish",
    "title": "祝融",
    "title_plain": "祝融",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:38:07",
    "modified": "2017-06-15 17:38:07",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/69祝融夫人_Lv.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["祝融是《三国演义》中的虚构人物，不见于正史记载。据传说为火神祝融氏后裔，南蛮王孟获之妻。武艺高强，善使飞刀，是《三国演义》中写到的唯一真正上过战场的女性。曾与孟获一起抵抗蜀军，在两军阵前被赵云活捉，在诸葛亮七擒七纵孟获之后，随孟获投降蜀汉。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13147,
    "type": "post",
    "slug": "%e5%90%95%e7%bb%ae%e9%93%83",
    "url": "http://games.hoolai.com/cms/?p=13147",
    "status": "publish",
    "title": "吕绮铃",
    "title_plain": "吕绮铃",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:33:58",
    "modified": "2017-06-15 17:33:58",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/68吕绮铃_Lv.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["为吕布与严氏所生之女孩。虽为吕布于为李傕所败，逃离长安之时遭遗留，但为庞舒藏匿后平安护送至吕布之处。尔后，虽与袁术之子曾有政治婚姻之提议，但于前往寿春途中被带回。当吕布于下邳遭曹操包围之时，联姻之事再次提及，但却为曹操及刘备所阻止。吕布死后，家眷被迁往许昌。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13146,
    "type": "post",
    "slug": "%e9%bb%84%e6%9c%88%e8%8b%b1-2",
    "url": "http://games.hoolai.com/cms/?p=13146",
    "status": "publish",
    "title": "黄月英",
    "title_plain": "黄月英",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:28:13",
    "modified": "2017-06-16 11:29:19",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/67黄月英_Lv.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["黄夫人，本名不详，传说名为黄月英、黄阿丑、黄婉贞。三国时荆州沔南白水（今湖北襄阳）人，沔阳名士黄承彦之女，诸葛亮之妻。史称其长相丑陋，黄头发，黑皮肤，但才华却与诸葛亮相当 。并小说《三国演义》里，罗贯中也对其进行了描述。后世流传诸葛亮与黄月英的动人传说，不过并未有史书证实，为美好的臆想罢了。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13145,
    "type": "post",
    "slug": "%e5%91%a8%e7%91%9c-2",
    "url": "http://games.hoolai.com/cms/?p=13145",
    "status": "publish",
    "title": "周瑜",
    "title_plain": "周瑜",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:27:04",
    "modified": "2017-06-15 17:27:04",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/63周瑜.png"],
      "初始品质": ["橙色"],
      "武将类型": ["辅助"],
      "描述": ["周瑜，字公瑾，东汉末年名将，安徽庐江舒县人。长壮有姿貌、精音律，江东有“曲有误，周郎顾”之语。周瑜少与孙策交好，后孙策遇刺身亡，孙权继任，周瑜将兵赴丧。建安十三年 （208年），周瑜率江东孙氏集团军队与刘备军队联合，赤壁之战大败曹军，由此奠定了三分天下的基础。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13144,
    "type": "post",
    "slug": "%e5%91%a8%e6%b3%b0-2",
    "url": "http://games.hoolai.com/cms/?p=13144",
    "status": "publish",
    "title": "周泰",
    "title_plain": "周泰",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:25:56",
    "modified": "2017-06-15 17:25:56",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/62周泰.png"],
      "初始品质": ["紫色"],
      "武将类型": ["防御"],
      "描述": ["周泰，字幼平，九江下蔡（今安徽凤台）人。孙策平定江东时与同郡蒋钦一起加入孙策军，随孙策左右，后孙权爱其为人，向孙策请求让周泰跟随自己。周泰多次于战乱当中保护孙权的安危，身上受的伤多达几十处，就像在皮肤上雕画一样。后来孙权为了表彰周泰为了东吴出生入死的功绩，而赐给他青罗伞盖。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13143,
    "type": "post",
    "slug": "%e8%b5%b5%e4%ba%91-2",
    "url": "http://games.hoolai.com/cms/?p=13143",
    "status": "publish",
    "title": "赵云",
    "title_plain": "赵云",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:24:42",
    "modified": "2017-06-16 16:00:32",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/60赵云.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["赵云，字子龙，常山真定（今河北省正定）人。身长八尺，姿颜雄伟，三国时期蜀汉名将。赵云跟随刘备将近三十年，先后参加过博望坡之战、长坂坡之战、江南平定战。除此，赵云于平定益州时引霍去病故事劝谏刘备将田宅归还百姓，又于关羽张飞被害之后劝谏刘备不要伐吴，被后世赞为有大臣局量的儒将。于建兴七年寿终正寝。景耀四年（公元261年），刘禅下令追谥赵云，姜维与众臣商议后建议刘禅追谥赵云为顺平侯。"],
      "可晋升": ["橙色"],
      "获取途径": ["首充礼包"],
      "首页": ["否"]
    }
  }, {
    "id": 13142,
    "type": "post",
    "slug": "%e5%bc%a0%e8%be%bd-2",
    "url": "http://games.hoolai.com/cms/?p=13142",
    "status": "publish",
    "title": "张辽",
    "title_plain": "张辽",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:19:36",
    "modified": "2017-06-15 17:19:36",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/55张辽.png"],
      "初始品质": ["紫色"],
      "武将类型": ["防御"],
      "描述": ["张辽，字文远，雁门马邑（今山西朔州）人。三国时期曹魏著名将领。与关羽同解白马围，降昌豨于东海，攻袁尚于邺城，率先锋在白狼山斩杀乌桓单于蹋顿。在建安二十年（215年）的合肥之战，张辽率800将士冲击孙权十万大军，打到了孙权的主帅旗之下，令孙权闻风丧胆。后以七千之众大破十万大军，差点活捉孙权。经此一役，张辽威震江东，声名大噪，“张辽止啼”也成为民间流传的传奇故事。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13141,
    "type": "post",
    "slug": "%e5%bc%a0%e9%83%83-2",
    "url": "http://games.hoolai.com/cms/?p=13141",
    "status": "publish",
    "title": "张郃",
    "title_plain": "张郃",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:17:53",
    "modified": "2017-06-15 18:05:11",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/52张郃.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["张郃，字儁乂，河间鄚人。在官渡之战中投降曹操。此后，随曹操攻乌桓、破马超、降张鲁，屡建战功。215年，率军进攻巴西宕渠，被蜀将张飞击败。219年，从夏侯渊迎战刘备军于定军山，当夏侯渊战死，全军危急之际，张郃代帅，率部安全撤退。228年，随曹真西拒诸葛亮，在街亭大败蜀军，迫其退回汉中。231年，领兵追击蜀军，至木门中箭亡。张郃戎马一生，以用兵巧变、善列营阵，长于利用地形著称。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["否"]
    }
  }, {
    "id": 13140,
    "type": "post",
    "slug": "%e5%bc%a0%e9%a3%9e-2",
    "url": "http://games.hoolai.com/cms/?p=13140",
    "status": "publish",
    "title": "张飞",
    "title_plain": "张飞",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:16:33",
    "modified": "2017-06-15 17:16:33",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/51张飞.png"],
      "初始品质": ["橙色"],
      "武将类型": ["攻击"],
      "描述": ["张飞，字益德，幽州涿郡（今河北省保定市涿州市）人，三国时期蜀汉名将。刘备长坂坡败退，张飞仅率二十骑断后，据水断桥，曹军没人敢逼近；与诸葛亮、赵云扫荡西川时，于江州义释严颜；汉中之战时又于宕渠击败张郃，对蜀汉贡献极大，后被范强、张达刺杀。在中国传统文化中，张飞以其勇猛、鲁莽、嫉恶如仇而著称，虽然此形象主要来源于小说和戏剧等民间艺术，但已深入人心。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13139,
    "type": "post",
    "slug": "%e5%a4%8f%e4%be%af%e6%83%87-2",
    "url": "http://games.hoolai.com/cms/?p=13139",
    "status": "publish",
    "title": "夏侯惇",
    "title_plain": "夏侯惇",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:15:10",
    "modified": "2017-06-15 18:07:17",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/43夏侯惇.png"],
      "初始品质": ["橙色"],
      "武将类型": ["攻击"],
      "描述": ["夏侯惇，字元让，沛国谯（今安徽亳州）人。东汉末年名将，曹魏开国元勋，西汉开国元勋夏侯婴的后代。曹操起兵，夏侯惇是其最早的将领之一。多次为曹操镇守后方，曾率军民阻断太寿河水，筑陂塘灌溉农田，使百姓受益，功勋卓著。夏侯惇一生虽多在军旅，但仍不忘治学。他常亲自迎师，虚心求教。他为人俭朴，所得赏赐全部分给将士。一生不置产业，至死家无余财。"],
      "可晋升": ["橙色"],
      "获取途径": ["防御"],
      "首页": ["否"]
    }
  }, {
    "id": 13138,
    "type": "post",
    "slug": "%e9%ad%8f%e5%bb%b6-2",
    "url": "http://games.hoolai.com/cms/?p=13138",
    "status": "publish",
    "title": "魏延",
    "title_plain": "魏延",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:13:29",
    "modified": "2017-06-16 16:01:13",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/41魏延.png"],
      "初始品质": ["紫色"],
      "武将类型": ["防御"],
      "描述": ["魏延，字文长，义阳（今河南桐柏）人。三国时期蜀汉名将，深受刘备器重。魏延镇守汉中近十年，之后又屡次随诸葛亮北伐，功绩显著。期间魏延多次请诸葛亮给他统领一万兵，另走一路攻关中，最后与诸葛亮会师于潼关，如同韩信的例子，但诸葛亮一直不许，因而认为自己无法完全发挥才能，心怀不满。与长史杨仪不和，诸葛亮死后，两人矛盾激化，相互争权，魏延败逃，为马岱所追斩，并被夷灭三族。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["否"]
    }
  }, {
    "id": 13128,
    "type": "post",
    "slug": "%e7%8e%8b%e6%9c%97",
    "url": "http://games.hoolai.com/cms/?p=13128",
    "status": "publish",
    "title": "王朗",
    "title_plain": "王朗",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:06:18",
    "modified": "2017-06-15 18:07:52",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/40王朗.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["王朗，字景兴。东海郯（今山东郯城西北）人。汉末至三国曹魏时期重臣、经学家。其孙女王元姬，嫁于晋王司马昭，生晋武帝司马炎、齐献王司马攸。王朗学识渊博，与其子王肃都为经学大家。著有《周易传》、《春秋传》、《孝经传》、《周官传》等，有文集三十四卷。在《三国演义中》诸葛亮北伐时，王朗不顾已经76岁之高龄，与曹真等人于祁山迎战诸葛亮。在阵前与诸葛亮挑起舌战，然而被诸葛亮的言词所驳倒，一时气愤而自马背上摔落而死。被称为“武乡侯骂死王朗”"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["否"]
    }
  }, {
    "id": 13127,
    "type": "post",
    "slug": "%e7%94%b0%e4%b8%b0",
    "url": "http://games.hoolai.com/cms/?p=13127",
    "status": "publish",
    "title": "田丰",
    "title_plain": "田丰",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:05:38",
    "modified": "2017-06-15 17:05:38",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/39田丰.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["田丰，字元皓，钜鹿（今河北巨鹿一带）人，一说渤海人。东汉末年袁绍部下谋臣，官至冀州别驾。其为人刚直，曾多次向袁绍进言而不被采纳，曹操部下谋臣荀彧曾评价他“刚而犯上”。后因谏阻袁绍征伐曹操而被袁绍下令监禁。官渡之战后，田丰被袁绍杀害。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13126,
    "type": "post",
    "slug": "%e5%a4%aa%e5%8f%b2%e6%85%88-2",
    "url": "http://games.hoolai.com/cms/?p=13126",
    "status": "publish",
    "title": "太史慈",
    "title_plain": "太史慈",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:04:43",
    "modified": "2017-06-15 17:04:43",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/38太史慈.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["太史慈（166年－206年），字子义，东莱黄县（今山东龙口东黄城集）人。东汉末年名将，官至建昌都尉。弓马熟练，箭法精良。建安十一年（206年）太史慈逝世，死前说道：“丈夫生世，当带三尺之剑，以升天子之阶。今所志未从，奈何而死乎！”"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13125,
    "type": "post",
    "slug": "%e5%ad%99%e7%ad%96-2",
    "url": "http://games.hoolai.com/cms/?p=13125",
    "status": "publish",
    "title": "孙策",
    "title_plain": "孙策",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:03:50",
    "modified": "2017-06-15 17:03:50",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/34孙策.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["孙策（175年—200年），字伯符，吴郡富春（今浙江富阳）人。孙坚长子，孙权长兄。东汉末年割据江东一带的军阀，汉末群雄之一，三国时期孙吴的奠基者之一。《三国演义》中绰号“小霸王”。为继承父亲孙坚的遗业而屈事袁术，后脱离袁术，统一江东。在一次狩猎中为刺客所伤，不久后身亡，年仅二十六岁。其弟孙权接掌孙策势力，并于称帝后，追谥孙策为长沙桓王。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13124,
    "type": "post",
    "slug": "%e6%bd%98%e5%87%a4",
    "url": "http://games.hoolai.com/cms/?p=13124",
    "status": "publish",
    "title": "潘凤",
    "title_plain": "潘凤",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:03:10",
    "modified": "2017-06-15 17:03:10",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/33潘凤.png"],
      "初始品质": ["紫色"],
      "武将类型": ["防御"],
      "描述": ["潘凤，是罗贯中的小说《三国演义》中的人物。而如今的潘凤则因为种种原因，以“无双上将”的身份成为新文学形象，而在网络上广泛流传。“上将潘凤”也成为三国人物中备受瞩目的人物形象之一。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13123,
    "type": "post",
    "slug": "%e9%a9%ac%e8%b6%85-2",
    "url": "http://games.hoolai.com/cms/?p=13123",
    "status": "publish",
    "title": "马超",
    "title_plain": "马超",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:02:13",
    "modified": "2017-06-15 17:02:13",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/32马超.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["马超，字孟起，司隶部扶风郡茂陵（今陕西杨凌五泉镇）人，东汉卫尉马腾之子，汉末群雄之一，蜀汉开国名将。带头上表刘协扶刘备称王，又辅佐刘备称帝。于章武二年十二月病逝（223年1月），终年47岁，追谥威侯。有阵中剑术“出手法”流传后世。《三国演义》及民间文化中称“三国英雄算马超”，因俊秀容貌与狮盔银铠的非凡装束而得名“锦马超”，有“不减吕布之勇”。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13122,
    "type": "post",
    "slug": "%e9%99%86%e9%80%8a-2",
    "url": "http://games.hoolai.com/cms/?p=13122",
    "status": "publish",
    "title": "陆逊",
    "title_plain": "陆逊",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 17:01:07",
    "modified": "2017-06-15 17:01:07",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/29陆逊.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["陆逊（183年—245年3月19日），本名陆议，字伯言，吴郡吴县（今江苏苏州）人。三国时期吴国政治家、军事家。章武二年（222年），孙权以陆逊为大都督，在夷陵火烧连营击败刘备，一战成名。陆逊跟随孙权四十余年，统领吴国军政十余年，深得孙权器重。深谋远虑，忠诚刚直。一生出将入相，被赞为“社稷之臣”。"],
      "可晋升": ["橙色"],
      "获取途径": ["VIP礼包"],
      "首页": ["是"]
    }
  }, {
    "id": 13121,
    "type": "post",
    "slug": "%e9%b2%81%e8%82%83-2",
    "url": "http://games.hoolai.com/cms/?p=13121",
    "status": "publish",
    "title": "鲁肃",
    "title_plain": "鲁肃",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:59:48",
    "modified": "2017-06-15 16:59:48",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/28鲁肃.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["鲁肃，字子敬，汉族，临淮郡东城县（今安徽定远）人，中国东汉末年杰出战略家、外交家。性格豪爽，喜读书、好骑射。周瑜因缺粮向鲁肃求助，鲁肃将一仓三千斛粮食慷慨赠给周瑜。建安十三年，曹操率大军南下。孙权部下多主降，而鲁肃与周瑜力排众议，坚决主战。结果，孙、刘联军大败曹军于赤壁，从此，奠定了三国鼎立格局。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13120,
    "type": "post",
    "slug": "%e5%bb%96%e5%8c%96",
    "url": "http://games.hoolai.com/cms/?p=13120",
    "status": "publish",
    "title": "廖化",
    "title_plain": "廖化",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:58:44",
    "modified": "2017-06-15 16:58:44",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/22廖化.png"],
      "初始品质": ["蓝色"],
      "武将类型": ["防御"],
      "描述": ["廖化，字元俭，荆州襄阳郡中卢县（今湖北省襄阳市）人。曾为关羽主簿，关羽败亡后归入孙吴，用诈死之计回归蜀汉，刘备授任为宜都郡太守。刘备去世后，为丞相参军，后为广武都督，迁阴平郡太守，多次参与蜀汉的北伐。官至右车骑将军，假节，领并州刺史，封中乡侯。蜀汉灭亡后，徙往洛阳，在中途病逝。廖化以果敢刚直著称，是蜀汉后期的重要将领。"],
      "可晋升": ["橙色"],
      "获取途径": ["酒馆"],
      "首页": ["是"]
    }
  }, {
    "id": 13112,
    "type": "post",
    "slug": "%e8%b4%be%e8%af%a9-2",
    "url": "http://games.hoolai.com/cms/?p=13112",
    "status": "publish",
    "title": "贾诩",
    "title_plain": "贾诩",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:54:57",
    "modified": "2017-06-15 16:54:57",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/19贾诩.png"],
      "初始品质": ["橙色"],
      "武将类型": ["攻击"],
      "描述": ["贾诩（147年－223年8月11日），字文和，凉州姑臧（今甘肃武威市凉州区）人。东汉末年至三国初年著名谋士、军事战略家，曹魏开国功臣。原为董卓部将，董卓死后，献计李傕、郭汜反攻长安。李傕等人失败后，辗转成为张绣的谋士。张绣曾用他的计策两次打败曹操，官渡之战前他劝张绣归降曹操。"],
      "获取途径": ["充值排行榜"],
      "可晋升": ["橙色"],
      "首页": ["是"]
    }
  }, {
    "id": 13111,
    "type": "post",
    "slug": "%e8%92%8b%e5%b9%b2",
    "url": "http://games.hoolai.com/cms/?p=13111",
    "status": "publish",
    "title": "蒋干",
    "title_plain": "蒋干",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:53:08",
    "modified": "2017-06-15 16:53:08",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/18蒋干.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["蒋干，字子翼，汉末三国时期的人物，九江（治今安徽寿县）人。历史上的蒋干是当时的名士，而罗贯中在历史小说《三国演义》中则将蒋干刻画成了被周瑜所愚弄的小丑形象。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13110,
    "type": "post",
    "slug": "%e5%8d%8e%e9%9b%84-2",
    "url": "http://games.hoolai.com/cms/?p=13110",
    "status": "publish",
    "title": "华雄",
    "title_plain": "华雄",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:52:06",
    "modified": "2017-06-15 16:52:06",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/16华雄.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["华雄，东汉末年董卓部下的武将，为董卓帐下都督。公元191年，关东军阀联合讨伐董卓，时任长沙太守的孙坚大破董卓军，华雄在此战中被孙坚一军所杀。明·罗贯中所著历史小说《三国演义》中则对这段历史作了改动，描写华雄被刘备二弟关羽所杀，这段被称为“温酒斩华雄”的故事情节也流传于后世。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13109,
    "type": "post",
    "slug": "%e9%bb%84%e5%bf%a0-2",
    "url": "http://games.hoolai.com/cms/?p=13109",
    "status": "publish",
    "title": "黄忠",
    "title_plain": "黄忠",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:50:28",
    "modified": "2017-06-15 16:50:28",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/15黄忠.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["黄忠，字汉升，南阳（今河南南阳）人。东汉末年名将。本为刘表部下中郎将，后归刘备，并助刘备攻益州刘璋。建安二十四年（219年），黄忠在定军山一战中阵斩曹操部下名将夏侯渊，升任征西将军，刘备称汉中王后改封后将军，赐关内侯。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13108,
    "type": "post",
    "slug": "%e7%94%98%e5%ae%81-2",
    "url": "http://games.hoolai.com/cms/?p=13108",
    "status": "publish",
    "title": "甘宁",
    "title_plain": "甘宁",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:49:24",
    "modified": "2017-06-15 16:49:24",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/11甘宁.png"],
      "初始品质": ["紫色"],
      "武将类型": ["攻击"],
      "描述": ["少年时好游侠，纠集人马，持弓弩，在地方上为非作歹，组成渠师抢夺船只财物，身佩铃铛，衣着华丽，人称锦帆贼。当地人闻铃响，即知道是甘宁出现。夺取船货直到二十多岁，后停止抢劫，熟读诸子。18岁左右任过蜀郡丞，后历仕于刘表和黄祖麾下不被重用，期间曾射杀凌统之父凌操，因此与凌统有杀父之仇。的大臣。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13106,
    "type": "post",
    "slug": "%e6%b3%95%e6%ad%a3",
    "url": "http://games.hoolai.com/cms/?p=13106",
    "status": "publish",
    "title": "法正",
    "title_plain": "法正",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:47:02",
    "modified": "2017-06-15 16:47:02",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/10法正.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["法正，字孝直，扶风郿（今陕西省眉县小法仪镇）人，东汉末年刘备帐下谋士，名士法真之孙。原为刘璋部下，刘备围成都时劝说刘璋投降，而后又与刘备进取汉中，献计将曹操大将夏侯渊斩首。刘备进位汉中王，封法正为尚书令、护军将军。次年，法正去世，终年四十五岁。法正之死令刘备十分感伤，连哭数日。被追谥为翼侯，是刘备时代唯一一位有谥号的大臣。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13102,
    "type": "post",
    "slug": "%e7%a8%8b%e6%98%b1",
    "url": "http://games.hoolai.com/cms/?p=13102",
    "status": "publish",
    "title": "程昱",
    "title_plain": "程昱",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:38:58",
    "modified": "2017-06-15 16:38:58",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/6程昱1.png"],
      "初始品质": ["紫色"],
      "武将类型": ["辅助"],
      "描述": ["本名程立，因梦中在泰山捧日，更名程昱。曾于东阿率领民众抗击黄巾。初平三年（192年），被曹操征辟为寿张令，从此为其出谋献策、征战四方。曹操征徐州时，程昱与荀彧留守后方，阻吕布、陈宫大军，保住三城，因功受封为东平相，屯于范县。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 13100,
    "type": "post",
    "slug": "%e6%9b%b9%e6%b4%aa",
    "url": "http://games.hoolai.com/cms/?p=13100",
    "status": "publish",
    "title": "曹洪",
    "title_plain": "曹洪",
    "content": "",
    "excerpt": "",
    "date": "2017-06-15 16:37:17",
    "modified": "2017-06-15 16:37:17",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 46,
      "slug": "liuchang",
      "name": "刘, 畅",
      "first_name": "畅",
      "last_name": "刘",
      "nickname": "liuchang",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/2曹洪1.png"],
      "初始品质": ["蓝色"],
      "武将类型": ["辅助"],
      "描述": ["曹洪早年随曹操起兵讨伐董卓。曹操于荥阳兵败失马时，曹洪舍命献马，并救护曹操，使其免于厄难。后多随军征伐，平兖州、征刘表、讨祝臂。官渡之战时，曹操令其驻守本阵。汉中之战时，与曹休在下辩抵御刘备，破斩吴兰、任夔，逼退张飞与马超。"],
      "可晋升": ["橙色"],
      "获取途径": ["过关令商店"],
      "首页": ["是"]
    }
  }, {
    "id": 12668,
    "type": "post",
    "slug": "%e6%9b%b9%e6%93%8d-4",
    "url": "http://games.hoolai.com/cms/?p=12668",
    "status": "publish",
    "title": "典韦",
    "title_plain": "典韦",
    "content": "",
    "excerpt": "",
    "date": "2017-06-12 17:52:24",
    "modified": "2017-06-15 16:44:22",
    "categories": [{
      "id": 437,
      "slug": "hulaisanguo2-youxiziliao-wujiang",
      "title": "胡莱三国2-游戏资料-武将",
      "description": "",
      "parent": 432,
      "post_count": 36
    }],
    "tags": [],
    "author": {
      "id": 42,
      "slug": "liboyi",
      "name": "李博毅",
      "first_name": "博毅",
      "last_name": "李",
      "nickname": "李博毅",
      "url": "",
      "description": ""
    },
    "comments": [],
    "attachments": [],
    "comment_count": 0,
    "comment_status": "closed",
    "custom_fields": {
      "武将icon": ["http://games.hoolai.com/cms/wp-content/uploads/2017/06/8典韦.png"],
      "初始品质": ["紫色"],
      "武将类型": ["防御"],
      "描述": ["典韦，陈留己吾（今河南商丘市宁陵县己吾城村）人。东汉末年曹操部将，相貌魁梧，膂力过人。本属张邈，后归曹操。曹操征讨吕布时被募为陷阵，表现英勇，被拜为校尉，宿卫曹操。建安二年（197年），张绣背叛曹操，典韦为保护曹操而独挡叛军，击杀多人，但最终因寡不敌众而战死。"],
      "可晋升": ["橙色"],
      "获取途径": ["擂台商店"],
      "首页": ["是"]
    }
  }]
}
